#!/usr/bin/env python3
#
# Emit a standalone CMake recipe for a resolved CON80 worklist.
#
# con80build --emit-cmake FILE
#
# Structure:
#   * cache variables (PYTHON/HALSC/PASS_REL32/MLIB/CON80/OUT/...)
#   * one add_custom_command per ASM/patch source
#   * the HAL units as a serial chain in topological order, using
#     the same logic that con80build does.
#   * the display decks (dfg -> preprocess -> halsc with scratch TEMPLIB),
#   * the lnk101 link of whichever worklist objects exist.
#
from __future__ import annotations

import os
import shlex
from pathlib import Path

from ap101Utils import halorder


def _q(p) -> str:
    return str(p)


def _sh(script: str) -> str:
    return script.replace('"', '\\"')




def emit(outfile: Path, *, root: str, by_type: dict, patches: dict,
         srcdirs, con80_dir: Path, mlib: Path | None, incl80: Path | None,
         deck_root: Path | None, out_root: Path, python: str, halsc: str,
         pass_rel32: Path, tolerable: int, linklibs, concard_root: str,
         allow_undefined: bool, nocall: bool = False) -> None:
    """Write the CMake recipe for the resolved worklist to `outfile`."""
    src_root = Path(__file__).resolve().parent.parent          # .../sdl/src
    srcdirs = [Path(d).resolve() for d in srcdirs]
    asm_sources = by_type["ASM"]
    hal_worklist = by_type["HAL"]
    # AMT decks (CDAPnn) ride the display recipe: the dfg CLI auto-detects
    # the deck form and the generate -> preprocess -> halsc flow is shared.
    displays = by_type["DISPLAY"] + by_type.get("AMT", [])

    tree = halorder.tree_units(srcdirs)
    from .con80build import _deck_template_seeds
    disp_seeds = [d for p in displays for d in _deck_template_seeds(p)]
    extra, closure_seeds = halorder.template_closure(hal_worklist, tree,
                                                     disp_seeds)
    order = halorder.topo_order(list(hal_worklist) + list(extra))
    worklist_set = set(hal_worklist)

    referenced: set[str] = set(closure_seeds)
    queue = list(order)
    visited: set[Path] = set(queue)
    while queue:
        _, deps = halorder.parse_hal(queue.pop())
        for dep in deps:
            referenced.add(dep)
            ent = tree.get(dep)
            if ent is not None and ent[2] != "PROGRAM" and ent[0] not in visited:
                visited.add(ent[0])
                queue.append(ent[0])

    seeds = []                                   # (descored, full program name)
    for dn in sorted(referenced):
        ent = tree.get(dn)
        if ent is not None and ent[2] == "PROGRAM":
            seeds.append((dn, ent[1]))

    L: list[str] = []
    w = L.append
    w(f"""\
# {root}.cmake -- CON80 load build recipe
# Generated by: python -m con80.con80build --emit-cmake
# Worklist frozen from CON80 root {root} ({con80_dir})
#
# This file does not read the CON80 deck and does not run con80build;
# lnk101 consults the deck only for csect placement at link time.
# Use as a CMakeLists.txt (or include() it), then: cmake --build .
#
# worklist: {len(asm_sources)} ASM, {len(hal_worklist)} HAL \
(+{len(extra)} template-closure), {len(displays)} display, \
{len(patches)} patch, {len(seeds)} seeded program templates
cmake_minimum_required(VERSION 3.20)
project({root}-con80 NONE)
""")
    w(f"""\
set(PYTHON "{_q(python)}" CACHE FILEPATH \
"python with asm101/lnk101/dfg installed")
set(HALSC "{_q(halsc)}" CACHE FILEPATH "halsc compiler wrapper")
set(PASS_REL32 "{_q(pass_rel32)}" CACHE PATH "PASS.REL32V0 dir")
set(SRCROOT "{_q(src_root)}" CACHE PATH \
"sdl/src (PYTHONPATH for PASS helper scripts)")""")
    # The venv tools run through their installed wrappers (beside halsc)
    # when present — shorter, readable commands; else `${PYTHON} -m <tool>`.
    bindir = Path(halsc).parent
    wrappers = {t: bindir / t for t in ("asm101", "dfg", "lnk101")}
    wrappers = {t: p for t, p in wrappers.items()
                if p.is_file() and os.access(p, os.X_OK)}
    for t, p in sorted(wrappers.items()):
        w(f'set({t.upper()} "{_q(p)}" CACHE FILEPATH "{t} wrapper")')
    asm101_cmd = ('"${ASM101}"' if "asm101" in wrappers
                  else '"${PYTHON}" -m asm101')
    dfg_cmd = ("'${DFG}'" if "dfg" in wrappers else "'${PYTHON}' -m dfg")
    lnk101_cmd = ("'${LNK101}'" if "lnk101" in wrappers
                  else "'${PYTHON}' -m lnk101")
    if mlib is not None:
        w(f'set(MLIB "{_q(Path(mlib).resolve())}" CACHE PATH '
          '"asm101 macro/COPY library")')
    w(f'set(CON80 "{_q(Path(con80_dir).resolve())}" CACHE PATH '
      '"CON80 deck (lnk101 placement only)")')
    if displays and deck_root is not None:
        w(f'set(DECK_ROOT "{_q(Path(deck_root).resolve())}" CACHE PATH '
          '"dfg display deck root")')
    w(f'set(OUT "{_q(Path(out_root).resolve())}" CACHE PATH "output root")')
    w("")
    w("""\
set(OBJDIR "${OUT}/obj")
set(GEN "${OUT}/gen")
file(MAKE_DIRECTORY "${OBJDIR}" "${GEN}" "${GEN}/pp" "${GEN}/seeds" \
"${GEN}/stamps" "${GEN}/tmpl_obj" "${GEN}/displays" "${GEN}/haltree")
set(PYENV ${CMAKE_COMMAND} -E env PYTHONUTF8=1)
set(HALENV ${CMAKE_COMMAND} -E env PYTHONUTF8=1 \
"PYTHONPATH=${PASS_REL32}:${SRCROOT}")
set(INCENV ${CMAKE_COMMAND} -E env PYTHONUTF8=1 \
"PYTHONPATH=${SRCROOT}/XCOM-I:${PASS_REL32}:${SRCROOT}")
""")

    # ---- ASM + patch objects (independent -> parallel) ---------------------
    w("# ---- AP-101 assembly (parallel) ----")
    asm_objs: list[str] = []
    items = [(p, p.stem) for p in asm_sources]
    items += [(p, member) for p, member in sorted(patches.items())]
    for srcpath, objstem in items:
        obj = f"${{OBJDIR}}/{objstem}.obj"
        asm_objs.append(obj)
        src = _q(srcpath.resolve())
        w(f"""\
add_custom_command(OUTPUT "{obj}"
  COMMAND ${{PYENV}} {asm101_cmd} "--object={obj}" \
"--library=${{MLIB}}" --tolerable={tolerable} "{src}"
  DEPENDS "{src}"
  COMMENT "asm101 {srcpath.name} -> {objstem}.obj" VERBATIM)""")
    w("add_custom_target(asm ALL DEPENDS")
    for obj in asm_objs:
        w(f'  "{obj}"')
    w(")")
    w("")

    # ---- HAL chain ----------------------------------------------------------
    w("""\
# ---- HAL/S (serial chain: shared TEMPLIB, template order) ----
# Mirror the extensionless sources as *.hal for the PASS tools, then
# initialise TEMPLIB/INCLIB.""")
    mirror_dirs = [*srcdirs] + ([Path(incl80).resolve()] if incl80 else [])
    # The mirror runs through con80build._hal_mirror (not a plain ln -sf
    # loop) so any build-layer source rewrite (native-CARDTYPE comment
    # remaps) is materialized as a transformed copy in the mirror.
    mirror_loop = (
        "'${PYTHON}' -c 'import sys; "
        "from con80.con80build import _hal_mirror; "
        "_hal_mirror(sys.argv[1:-1], sys.argv[-1])' "
        + " ".join(f"'{d}'" for d in mirror_dirs)
        + " '${GEN}/haltree'")
    # Clearing TEMPLIB invalidates every HAL object: templates are inputs to
    # every unit, and a stale object would short-circuit the retry pass (its
    # template never re-enters the fresh TEMPLIB, starving dependent units).
    hal_objs = " ".join(f'"${{OBJDIR}}/{p.stem}.obj"' for p in order
                        if p in worklist_set)
    w(f"""\
add_custom_command(OUTPUT "${{GEN}}/stamps/hal_setup"
  COMMAND ${{HALENV}} sh -c "{_sh(mirror_loop)}"
  COMMAND ${{CMAKE_COMMAND}} -E rm -rf "${{GEN}}/TEMPLIB" "${{GEN}}/SDFLIB" \
"${{GEN}}/tmpl_obj"
  COMMAND ${{CMAKE_COMMAND}} -E make_directory "${{GEN}}/tmpl_obj" \
"${{GEN}}/stamps"
  COMMAND ${{CMAKE_COMMAND}} -E rm -f {hal_objs}
  COMMAND ${{HALENV}} "${{PYTHON}}" "${{PASS_REL32}}/prepareTEMPLIB" \
--clear""")
    if incl80:
        w('  COMMAND ${INCENV} "${PYTHON}" "${PASS_REL32}/prepareINCLIB"'
          f' --clear "--include=${{GEN}}/haltree/{Path(incl80).name}"')
    w("""\
  COMMAND ${CMAKE_COMMAND} -E touch "${GEN}/stamps/hal_setup"
  WORKING_DIRECTORY "${GEN}"
  COMMENT "hal setup: mirror + TEMPLIB/INCLIB init" VERBATIM)""")
    prev = '${GEN}/stamps/hal_setup'

    w("# Program-template seeds (cycle-break + externally-scheduled programs).")
    for dn, progname in seeds:
        stamp = f"${{GEN}}/stamps/seed_{dn}"
        seed_cmd = (f"'${{HALSC}}' '--parm={halorder.get_parms('_seed')}' "
                    f"'--templib=${{GEN}}/TEMPLIB' '--inclib=${{GEN}}/INCLIB' "
                    f"'--sdf=${{GEN}}/SDFLIB' "
                    f"'--workdir=${{GEN}}/_seed_{dn}.work' "
                    f"-o '${{GEN}}/_seed_{dn}.obj' '${{GEN}}/seeds/{dn}.hal' "
                    "|| true")
        w(f"""\
file(WRITE "${{GEN}}/seeds/{dn}.hal" \
" {progname}: PROGRAM;\\n CLOSE {progname};\\n")
add_custom_command(OUTPUT "{stamp}"
  COMMAND ${{HALENV}} sh -c "{_sh(seed_cmd)}"
  COMMAND ${{CMAKE_COMMAND}} -E touch "{stamp}"
  DEPENDS "{prev}" COMMENT "halsc seed {dn}" VERBATIM)""")
        prev = stamp

    w("""\
# Worklist + closure units, topological order.  A failed unit still
# stamps (its object is simply absent), so the chain and link proceed.""")
    for p in order:
        stem = p.stem
        dest = "${OBJDIR}" if p in worklist_set else "${GEN}/tmpl_obj"
        obj = f"{dest}/{stem}.obj"
        pp = f"${{GEN}}/pp/{stem}.hal"
        rel = f"{p.parent.name}/{p.name}.hal"
        parm = halorder.get_parms(stem)
        work = f"${{GEN}}/{stem}.work"
        stamp = f"${{GEN}}/stamps/hal_{stem}"
        # Units compile straight from the .hal mirror (materialized
        # rewrites included) — no preprocessHALSFC (its include hoisting
        # is inferred behavior the flight SDL never had; SDF includes
        # satisfy templates flight-style).
        pp_cmd = (f"cp '${{GEN}}/haltree/{rel}' '{pp}' "
                  f"|| cp '{_q(p.resolve())}' '{pp}'")
        halsc_cmd = (
            f"'${{HALSC}}' '--parm={parm}' '--templib=${{GEN}}/TEMPLIB' "
            f"'--inclib=${{GEN}}/INCLIB' '--sdf=${{GEN}}/SDFLIB' "
            f"'--workdir={work}' -o '{obj}' '{pp}' "
            f"|| {{ grep -q ZO3 '{work}/opt.rpt' 2>/dev/null && "
            f"'${{HALSC}}' '--parm={parm},X1' '--templib=${{GEN}}/TEMPLIB' "
            f"'--inclib=${{GEN}}/INCLIB' '--sdf=${{GEN}}/SDFLIB' "
            f"'--workdir={work}' -o '{obj}' '{pp}'; }} "
            f"|| echo 'halsc FAIL {stem}'")
        w(f"""\
add_custom_command(OUTPUT "{stamp}"
  COMMAND ${{HALENV}} sh -c "{_sh(pp_cmd)}"
  COMMAND ${{HALENV}} sh -c "{_sh(halsc_cmd)}"
  COMMAND ${{CMAKE_COMMAND}} -E touch "{stamp}"
  BYPRODUCTS "{obj}" "{pp}"
  DEPENDS "{_q(p.resolve())}" "{prev}"
  WORKING_DIRECTORY "${{GEN}}/haltree"
  COMMENT "halsc {stem}" VERBATIM)""")
        prev = stamp

    w("""\
# Retry passes: a unit blocked on a producer that only compiled later in
# pass 1 succeeds here (con80build's multi-pass).  The generated script
# re-attempts every unit still missing its object, in topological order,
# round after round until a round makes no progress -- template cycle
# clusters (e.g. the DM* displays) need several rounds to converge.""")
    w('file(WRITE "${GEN}/hal_retry.sh" [=[#!/bin/sh')
    w("""\
# multi-pass halsc retry (generated; env: HALSC GEN OBJDIR)
try() {
  obj="$2/$1.obj"
  [ -f "$obj" ] && return 0
  pp="$GEN/pp/$1.hal"; work="$GEN/$1.work"
  "$HALSC" "--parm=$3" "--templib=$GEN/TEMPLIB" "--inclib=$GEN/INCLIB" \\
      "--sdf=$GEN/SDFLIB" "--workdir=$work" -o "$obj" "$pp" \\
    || { grep -q ZO3 "$work/opt.rpt" 2>/dev/null && \\
         "$HALSC" "--parm=$3,X1" "--templib=$GEN/TEMPLIB" \\
         "--inclib=$GEN/INCLIB" "--sdf=$GEN/SDFLIB" \\
         "--workdir=$work" -o "$obj" "$pp"; }
  [ -f "$obj" ] && progress=1
  return 0
}
units() {""")
    for p in order:
        stem = p.stem
        dest = "$OBJDIR" if p in worklist_set else "$GEN/tmpl_obj"
        w(f'  "$1" {stem} "{dest}" {halorder.get_parms(stem)}')
    w("""\
}
round=1
while [ "$round" -le 10 ]; do
  progress=0
  units try
  [ "$progress" -eq 0 ] && break
  round=$((round+1))
done
fails=0
miss() { [ -f "$2/$1.obj" ] || { echo "halsc FAIL (retry) $1"; fails=$((fails+1)); }; }
units miss
echo "hal retry: converged after $round round(s), $fails unit(s) missing"
]=])""")
    stamp = "${GEN}/stamps/hal_retry"
    w(f"""\
add_custom_command(OUTPUT "{stamp}"
  COMMAND ${{HALENV}} "HALSC=${{HALSC}}" "GEN=${{GEN}}" "OBJDIR=${{OBJDIR}}" \
sh "${{GEN}}/hal_retry.sh"
  COMMAND ${{CMAKE_COMMAND}} -E touch "{stamp}"
  DEPENDS "{prev}"
  COMMENT "halsc retry (multi-pass, to convergence)" VERBATIM)""")
    prev = stamp
    w(f'add_custom_target(hal ALL DEPENDS "{prev}")')
    hal_end = prev
    w("")

    # ---- displays -----------------------------------------------------------
    if displays:
        w("""\
# ---- display decks (dfg -> preprocess -> halsc) ----
# dfg types the deck from the shared SDFLIB, and the compile includes
# from it too (--sdfi, input-only).  halsc's TEMPLATE parm appends each
# compiled unit's template, so displays compile against a scratch
# TEMPLIB copy (also the textual fallback); serialized for the same
# reason.""")
        disp_objs = " ".join(f'"${{OBJDIR}}/{p.stem}.obj"' for p in displays)
        w(f"""\
add_custom_command(OUTPUT "${{GEN}}/stamps/disp_setup"
  COMMAND ${{CMAKE_COMMAND}} -E rm -rf "${{GEN}}/disp_TEMPLIB"
  COMMAND ${{CMAKE_COMMAND}} -E rm -f {disp_objs}
  COMMAND ${{CMAKE_COMMAND}} -E copy_directory "${{GEN}}/TEMPLIB" \
"${{GEN}}/disp_TEMPLIB"
  COMMAND ${{CMAKE_COMMAND}} -E touch "${{GEN}}/stamps/disp_setup"
  DEPENDS "{hal_end}" COMMENT "scratch TEMPLIB for displays" VERBATIM)""")
        prev = '${GEN}/stamps/disp_setup'
        for p in displays:
            name = p.stem
            hal_out = f"${{GEN}}/displays/{name}.hal"
            pp = f"${{GEN}}/displays/{name}.pp.hal"
            obj = f"${{OBJDIR}}/{name}.obj"
            work = f"${{GEN}}/displays/{name}.work"
            stamp = f"${{GEN}}/stamps/disp_{name}"
            deck_opt = " --deck-root '${DECK_ROOT}'" if deck_root else ""
            cmd = (
                f"{dfg_cmd} {name} --sdflib '${{GEN}}/SDFLIB'"
                f"{deck_opt} -o '{hal_out}' && "
                f"cp '{hal_out}' '{pp}' && "
                f"'${{HALSC}}' '--parm={halorder.get_parms(name)}' "
                f"'--templib=${{GEN}}/disp_TEMPLIB' '--inclib=${{GEN}}/INCLIB' "
                f"'--sdfi=${{GEN}}/SDFLIB' "
                f"'--workdir={work}' -o '{obj}' '{pp}' "
                f"|| echo 'display FAIL {name}'")
            w(f"""\
add_custom_command(OUTPUT "{stamp}"
  COMMAND ${{HALENV}} sh -c "{_sh(cmd)}"
  COMMAND ${{CMAKE_COMMAND}} -E touch "{stamp}"
  BYPRODUCTS "{obj}"
  DEPENDS "{_q(p.resolve())}" "{prev}"
  WORKING_DIRECTORY "${{GEN}}/haltree"
  COMMENT "display {name}" VERBATIM)""")
            prev = stamp
        w(f'add_custom_target(displays ALL DEPENDS "{prev}")')
    disp_end = prev
    w("")

    # ---- link ---------------------------------------------------------------
    w("""\
# ---- link (lnk101 --concard: deck read for placement only) ----
# The worklist's objects, filtered at build time to those that built.""")
    w(f'file(WRITE "${{GEN}}/link_objs.txt"')
    link_names = ([p.stem for p in asm_sources]
                  + [p.stem for p in hal_worklist]
                  + [p.stem for p in displays]
                  + [member for member in patches.values()])
    for nm in link_names:
        w(f'  "${{OBJDIR}}/{nm}.obj\\n"')
    w(")")
    lnk_flags = f"--concard '${{CON80}}' --concard-root {concard_root} " \
                f"-o '${{OUT}}/{root}.fcm' " \
                f"--json-symbols '${{OUT}}/{root}.sym.json'"
    for lib in linklibs:
        lnk_flags += f" -L '{_q(Path(lib).resolve())}'"
    if allow_undefined:
        lnk_flags += " --allow-undefined"
    if nocall:
        lnk_flags += " --nocall"
    link_cmd = (
        "while read o; do [ -f $o ] && echo $o; done "
        "< '${GEN}/link_objs.txt' > '${GEN}/link_objs.live.txt'; "
        f"{lnk101_cmd} @'${{GEN}}/link_objs.live.txt' {lnk_flags}")
    w(f"""\
add_custom_command(OUTPUT "${{OUT}}/{root}.fcm"
  COMMAND ${{PYENV}} sh -c "{_sh(link_cmd)}"
  DEPENDS asm "{disp_end}" "${{GEN}}/link_objs.txt"
  COMMENT "lnk101 -> {root}.fcm" VERBATIM)
add_custom_target(fcm ALL DEPENDS "${{OUT}}/{root}.fcm")
""")

    outfile = Path(outfile)
    outfile.parent.mkdir(parents=True, exist_ok=True)
    outfile.write_text("\n".join(L) + "\n")
