#!/usr/bin/env python3
#
# Emit a standalone CMake recipe for a resolved CON80 worklist.
#
# con80build --emit-cmake FILE
#
# Structure:
#   * cache variables (PYTHON/HALSC/PASS_REL32/MLIB/CON80/OUT/...)
#   * one add_custom_command per ASM/patch source
#   * the HAL units as a serial chain in topological order, using
#     the same logic that con80build does.
#   * the display decks (dfg -> preprocess -> halsc with scratch TEMPLIB),
#   * the lnk101 link of whichever worklist objects exist.
#
from __future__ import annotations

import shlex
from pathlib import Path

from . import halorder


def _q(p) -> str:
    return str(p)


def _sh(script: str) -> str:
    return script.replace('"', '\\"')


def emit(outfile: Path, *, root: str, by_type: dict, patches: dict,
         srcdirs, con80_dir: Path, mlib: Path | None, incl80: Path | None,
         deck_root: Path | None, out_root: Path, python: str, halsc: str,
         pass_rel32: Path, tolerable: int, linklibs, concard_root: str,
         allow_undefined: bool) -> None:
    """Write the CMake recipe for the resolved worklist to `outfile`."""
    src_root = Path(__file__).resolve().parent.parent          # .../sdl/src
    srcdirs = [Path(d).resolve() for d in srcdirs]
    asm_sources = by_type["ASM"]
    hal_worklist = by_type["HAL"]
    displays = by_type["DISPLAY"]

    tree = halorder.tree_units(srcdirs)
    extra, closure_seeds = halorder.template_closure(hal_worklist, tree)
    order = halorder.topo_order(list(hal_worklist) + list(extra))
    worklist_set = set(hal_worklist)

    referenced: set[str] = set(closure_seeds)
    queue = list(order)
    visited: set[Path] = set(queue)
    while queue:
        _, deps = halorder.parse_hal(queue.pop())
        for dep in deps:
            referenced.add(dep)
            ent = tree.get(dep)
            if ent is not None and ent[2] != "PROGRAM" and ent[0] not in visited:
                visited.add(ent[0])
                queue.append(ent[0])

    seeds = []                                   # (descored, full program name)
    for dn in sorted(referenced):
        ent = tree.get(dn)
        if ent is not None and ent[2] == "PROGRAM":
            seeds.append((dn, ent[1]))

    L: list[str] = []
    w = L.append
    w(f"""\
# {root}.cmake -- CON80 load build recipe
# Generated by: python -m ap101Utils.con80build --emit-cmake
# Worklist frozen from CON80 root {root} ({con80_dir})
#
# This file does not read the CON80 deck and does not run con80build;
# lnk101 consults the deck only for csect placement at link time.
# Use as a CMakeLists.txt (or include() it), then: cmake --build .
#
# worklist: {len(asm_sources)} ASM, {len(hal_worklist)} HAL \
(+{len(extra)} template-closure), {len(displays)} display, \
{len(patches)} patch, {len(seeds)} seeded program templates
cmake_minimum_required(VERSION 3.20)
project({root}-con80 NONE)
""")
    w(f"""\
set(PYTHON "{_q(python)}" CACHE FILEPATH \
"python with asm101/lnk101/dfg installed")
set(HALSC "{_q(halsc)}" CACHE FILEPATH "halsc compiler wrapper")
set(PASS_REL32 "{_q(pass_rel32)}" CACHE PATH "PASS.REL32V0 dir")
set(SRCROOT "{_q(src_root)}" CACHE PATH \
"sdl/src (PYTHONPATH for PASS helper scripts)")""")
    if mlib is not None:
        w(f'set(MLIB "{_q(Path(mlib).resolve())}" CACHE PATH '
          '"asm101 macro/COPY library")')
    w(f'set(CON80 "{_q(Path(con80_dir).resolve())}" CACHE PATH '
      '"CON80 deck (lnk101 placement only)")')
    if displays and deck_root is not None:
        w(f'set(DECK_ROOT "{_q(Path(deck_root).resolve())}" CACHE PATH '
          '"dfg display deck root")')
    w(f'set(OUT "{_q(Path(out_root).resolve())}" CACHE PATH "output root")')
    w("")
    w("""\
set(OBJDIR "${OUT}/obj")
set(GEN "${OUT}/gen")
file(MAKE_DIRECTORY "${OBJDIR}" "${GEN}" "${GEN}/pp" "${GEN}/seeds" \
"${GEN}/stamps" "${GEN}/tmpl_obj" "${GEN}/displays" "${GEN}/haltree")
set(PYENV ${CMAKE_COMMAND} -E env PYTHONUTF8=1)
set(HALENV ${CMAKE_COMMAND} -E env PYTHONUTF8=1 \
"PYTHONPATH=${PASS_REL32}:${SRCROOT}")
set(INCENV ${CMAKE_COMMAND} -E env PYTHONUTF8=1 \
"PYTHONPATH=${SRCROOT}/XCOM-I:${PASS_REL32}:${SRCROOT}")
""")

    # ---- ASM + patch objects (independent -> parallel) ---------------------
    w("# ---- AP-101S assembly (parallel) ----")
    asm_objs: list[str] = []
    items = [(p, p.stem) for p in asm_sources]
    items += [(p, member) for p, member in sorted(patches.items())]
    for srcpath, objstem in items:
        obj = f"${{OBJDIR}}/{objstem}.obj"
        asm_objs.append(obj)
        src = _q(srcpath.resolve())
        w(f"""\
add_custom_command(OUTPUT "{obj}"
  COMMAND ${{PYENV}} "${{PYTHON}}" -m asm101 "--object={obj}" \
"--library=${{MLIB}}" --tolerable={tolerable} "{src}"
  DEPENDS "{src}"
  COMMENT "asm101 {srcpath.name} -> {objstem}.obj" VERBATIM)""")
    w("add_custom_target(asm ALL DEPENDS")
    for obj in asm_objs:
        w(f'  "{obj}"')
    w(")")
    w("")

    # ---- HAL chain ----------------------------------------------------------
    w("""\
# ---- HAL/S (serial chain: shared TEMPLIB, template order) ----
# Mirror the extensionless sources as *.hal for the PASS tools, then
# initialise TEMPLIB/INCLIB.""")
    mirror_dirs = [*srcdirs] + ([Path(incl80).resolve()] if incl80 else [])
    mirror_loop = ("for d in " + " ".join(f"'{d}'" for d in mirror_dirs)
                   + "; do b=$(basename $d); mkdir -p '${GEN}/haltree/'$b; "
                   "for f in $d/*; do [ -f $f ] && ln -sf $f "
                   "'${GEN}/haltree/'$b/$(basename $f).hal; done; done; true")
    w(f"""\
add_custom_command(OUTPUT "${{GEN}}/stamps/hal_setup"
  COMMAND sh -c "{_sh(mirror_loop)}"
  COMMAND ${{CMAKE_COMMAND}} -E rm -rf "${{GEN}}/TEMPLIB"
  COMMAND ${{HALENV}} "${{PYTHON}}" "${{PASS_REL32}}/prepareTEMPLIB" \
--clear""")
    if incl80:
        w('  COMMAND ${INCENV} "${PYTHON}" "${PASS_REL32}/prepareINCLIB"'
          f' --clear "--include=${{GEN}}/haltree/{Path(incl80).name}"')
    w("""\
  COMMAND ${CMAKE_COMMAND} -E touch "${GEN}/stamps/hal_setup"
  WORKING_DIRECTORY "${GEN}"
  COMMENT "hal setup: mirror + TEMPLIB/INCLIB init" VERBATIM)""")
    prev = '${GEN}/stamps/hal_setup'

    w("# Program-template seeds (cycle-break + externally-scheduled programs).")
    for dn, progname in seeds:
        stamp = f"${{GEN}}/stamps/seed_{dn}"
        seed_cmd = (f"'${{HALSC}}' '--parm={halorder.get_parms('_seed')}' "
                    f"'--templib=${{GEN}}/TEMPLIB' '--inclib=${{GEN}}/INCLIB' "
                    f"'--workdir=${{GEN}}/_seed_{dn}.work' "
                    f"-o '${{GEN}}/_seed_{dn}.obj' '${{GEN}}/seeds/{dn}.hal' "
                    "|| true")
        w(f"""\
file(WRITE "${{GEN}}/seeds/{dn}.hal" \
" {progname}: PROGRAM;\\n CLOSE {progname};\\n")
add_custom_command(OUTPUT "{stamp}"
  COMMAND ${{HALENV}} sh -c "{_sh(seed_cmd)}"
  COMMAND ${{CMAKE_COMMAND}} -E touch "{stamp}"
  DEPENDS "{prev}" COMMENT "halsc seed {dn}" VERBATIM)""")
        prev = stamp

    w("""\
# Worklist + closure units, topological order.  A failed unit still
# stamps (its object is simply absent), so the chain and link proceed.""")
    for p in order:
        stem = p.stem
        dest = "${OBJDIR}" if p in worklist_set else "${GEN}/tmpl_obj"
        obj = f"{dest}/{stem}.obj"
        pp = f"${{GEN}}/pp/{stem}.hal"
        rel = f"{p.parent.name}/{p.name}.hal"
        parm = halorder.get_parms(stem)
        work = f"${{GEN}}/{stem}.work"
        stamp = f"${{GEN}}/stamps/hal_{stem}"
        pp_cmd = (f"'${{PYTHON}}' '${{PASS_REL32}}/preprocessHALSFC' "
                  f"'--in={rel}' '--out={pp}' && [ -f '{pp}' ] "
                  f"|| cp '{_q(p.resolve())}' '{pp}'")
        halsc_cmd = (
            f"'${{HALSC}}' '--parm={parm}' '--templib=${{GEN}}/TEMPLIB' "
            f"'--inclib=${{GEN}}/INCLIB' '--workdir={work}' -o '{obj}' '{pp}' "
            f"|| {{ grep -q ZO3 '{work}/opt.rpt' 2>/dev/null && "
            f"'${{HALSC}}' '--parm={parm},X1' '--templib=${{GEN}}/TEMPLIB' "
            f"'--inclib=${{GEN}}/INCLIB' '--workdir={work}' -o '{obj}' '{pp}'; }} "
            f"|| echo 'halsc FAIL {stem}'")
        w(f"""\
add_custom_command(OUTPUT "{stamp}"
  COMMAND ${{HALENV}} sh -c "{_sh(pp_cmd)}"
  COMMAND ${{HALENV}} sh -c "{_sh(halsc_cmd)}"
  COMMAND ${{CMAKE_COMMAND}} -E touch "{stamp}"
  BYPRODUCTS "{obj}" "{pp}"
  DEPENDS "{_q(p.resolve())}" "{prev}"
  WORKING_DIRECTORY "${{GEN}}/haltree"
  COMMENT "halsc {stem}" VERBATIM)""")
        prev = stamp

    w("""\
# Retry pass: a unit blocked on a producer that only compiled later in
# pass 1 succeeds here (con80build's multi-pass, unrolled once).  Units
# whose object already exists are skipped.""")
    for p in order:
        stem = p.stem
        dest = "${OBJDIR}" if p in worklist_set else "${GEN}/tmpl_obj"
        obj = f"{dest}/{stem}.obj"
        pp = f"${{GEN}}/pp/{stem}.hal"
        parm = halorder.get_parms(stem)
        work = f"${{GEN}}/{stem}.work"
        stamp = f"${{GEN}}/stamps/hal2_{stem}"
        retry_cmd = (
            f"[ -f '{obj}' ] || "
            f"'${{HALSC}}' '--parm={parm}' '--templib=${{GEN}}/TEMPLIB' "
            f"'--inclib=${{GEN}}/INCLIB' '--workdir={work}' -o '{obj}' '{pp}' "
            f"|| {{ grep -q ZO3 '{work}/opt.rpt' 2>/dev/null && "
            f"'${{HALSC}}' '--parm={parm},X1' '--templib=${{GEN}}/TEMPLIB' "
            f"'--inclib=${{GEN}}/INCLIB' '--workdir={work}' -o '{obj}' '{pp}'; }} "
            f"|| echo 'halsc FAIL (pass 2) {stem}'")
        w(f"""\
add_custom_command(OUTPUT "{stamp}"
  COMMAND ${{HALENV}} sh -c "{_sh(retry_cmd)}"
  COMMAND ${{CMAKE_COMMAND}} -E touch "{stamp}"
  DEPENDS "{prev}"
  WORKING_DIRECTORY "${{GEN}}/haltree"
  COMMENT "halsc retry {stem}" VERBATIM)""")
        prev = stamp
    w(f'add_custom_target(hal ALL DEPENDS "{prev}")')
    hal_end = prev
    w("")

    # ---- displays -----------------------------------------------------------
    if displays:
        w("""\
# ---- display decks (dfg -> preprocess -> halsc vs scratch TEMPLIB) ----
# halsc's TEMPLATE parm appends each compiled unit's template, so
# displays compile against a scratch copy; serialized for the same
# reason.""")
        w(f"""\
add_custom_command(OUTPUT "${{GEN}}/stamps/disp_setup"
  COMMAND ${{CMAKE_COMMAND}} -E rm -rf "${{GEN}}/disp_TEMPLIB"
  COMMAND ${{CMAKE_COMMAND}} -E copy_directory "${{GEN}}/TEMPLIB" \
"${{GEN}}/disp_TEMPLIB"
  COMMAND ${{CMAKE_COMMAND}} -E touch "${{GEN}}/stamps/disp_setup"
  DEPENDS "{hal_end}" COMMENT "scratch TEMPLIB for displays" VERBATIM)""")
        prev = '${GEN}/stamps/disp_setup'
        for p in displays:
            name = p.stem
            hal_out = f"${{GEN}}/displays/{name}.hal"
            pp = f"${{GEN}}/displays/{name}.pp.hal"
            obj = f"${{OBJDIR}}/{name}.obj"
            work = f"${{GEN}}/displays/{name}.work"
            stamp = f"${{GEN}}/stamps/disp_{name}"
            deck_opt = " --deck-root '${DECK_ROOT}'" if deck_root else ""
            cmd = (
                f"'${{PYTHON}}' -m dfg {name} --templib '${{GEN}}/TEMPLIB'"
                f"{deck_opt} -o '{hal_out}' && "
                f"{{ '${{PYTHON}}' '${{PASS_REL32}}/preprocessHALSFC' "
                f"'--in={hal_out}' '--out={pp}' && [ -f '{pp}' ] "
                f"|| cp '{hal_out}' '{pp}'; }} && "
                f"'${{HALSC}}' '--parm={halorder.get_parms(name)}' "
                f"'--templib=${{GEN}}/disp_TEMPLIB' '--inclib=${{GEN}}/INCLIB' "
                f"'--workdir={work}' -o '{obj}' '{pp}' "
                f"|| echo 'display FAIL {name}'")
            w(f"""\
add_custom_command(OUTPUT "{stamp}"
  COMMAND ${{HALENV}} sh -c "{_sh(cmd)}"
  COMMAND ${{CMAKE_COMMAND}} -E touch "{stamp}"
  BYPRODUCTS "{obj}"
  DEPENDS "{_q(p.resolve())}" "{prev}"
  WORKING_DIRECTORY "${{GEN}}/haltree"
  COMMENT "display {name}" VERBATIM)""")
            prev = stamp
        w(f'add_custom_target(displays ALL DEPENDS "{prev}")')
    disp_end = prev
    w("")

    # ---- link ---------------------------------------------------------------
    w("""\
# ---- link (lnk101 --concard: deck read for placement only) ----
# The worklist's objects, filtered at build time to those that built.""")
    w(f'file(WRITE "${{GEN}}/link_objs.txt"')
    link_names = ([p.stem for p in asm_sources]
                  + [p.stem for p in hal_worklist]
                  + [p.stem for p in displays]
                  + [member for member in patches.values()])
    for nm in link_names:
        w(f'  "${{OBJDIR}}/{nm}.obj\\n"')
    w(")")
    lnk_flags = f"--concard '${{CON80}}' --concard-root {concard_root} " \
                f"-o '${{OUT}}/{root}.fcm' " \
                f"--json-symbols '${{OUT}}/{root}.sym.json'"
    for lib in linklibs:
        lnk_flags += f" -L '{_q(Path(lib).resolve())}'"
    if allow_undefined:
        lnk_flags += " --allow-undefined"
    link_cmd = (
        "while read o; do [ -f $o ] && echo $o; done "
        "< '${GEN}/link_objs.txt' > '${GEN}/link_objs.live.txt'; "
        f"'${{PYTHON}}' -m lnk101 @'${{GEN}}/link_objs.live.txt' {lnk_flags}")
    w(f"""\
add_custom_command(OUTPUT "${{OUT}}/{root}.fcm"
  COMMAND ${{PYENV}} sh -c "{_sh(link_cmd)}"
  DEPENDS asm "{disp_end}" "${{GEN}}/link_objs.txt"
  COMMENT "lnk101 -> {root}.fcm" VERBATIM)
add_custom_target(fcm ALL DEPENDS "${{OUT}}/{root}.fcm")
""")

    outfile = Path(outfile)
    outfile.parent.mkdir(parents=True, exist_ok=True)
    outfile.write_text("\n".join(L) + "\n")
