#!/usr/bin/env python3
"""
Generate expected IBM DP hex values for HAL/S-FC float literal tests.

Bug under test: virtualagc issue #1296 — HALSFC converts 1.0E-8 to
0x3A2AF31D_C4611874, but the original IBM HAL/S-FC compiler produces
0x3A2AF31D_C4611873.

Root cause: the original IBM compiler routine XXXTOD.bal (in
PASS.REL32V0/MONITOR.ASM) builds the value using S/360 hardware hex
floating-point operations (MD, AD, MDR, DDR) which truncate the mantissa
to 14 hex digits at every step.  In particular, for 1.0E-8 the routine
computes 10.0 / 10**9 as a single hardware DDR; the true mantissa is
0.16777216... whose 15th hex digit is B — truncation drops it, giving
mantissa 0x2AF31DC4611873.  Our reimplementation goes through atof()
(losing precision via IEEE double), then llround() (round-half-away-
from-zero), giving 0x2AF31DC4611874.

Reference values below are computed by:
  1. Convert the literal to an exact Decimal.
  2. Multiply by 2^56 / 16^(e-64) to put the mantissa in [2^52, 2^56).
  3. Truncate (ROUND_DOWN) to an integer.

This matches IBM XXXTOD's behavior whenever the value can be expressed
exactly in IBM DP after a single hardware divide of two operands that
are themselves exactly representable — which covers all the cases
below (and the failing 1.0E-8 case from the issue).
"""
from decimal import Decimal, getcontext, ROUND_DOWN, ROUND_HALF_UP

getcontext().prec = 60

twoTo56 = Decimal(2 ** 56)
twoTo52 = Decimal(2 ** 52)


def to_ibm_dp(x_str: str, mode=ROUND_DOWN) -> tuple[int, int]:
    """Convert a decimal literal string to IBM double-precision hex float.

    Returns (msw, lsw) — two 32-bit unsigned integers.
    """
    d = Decimal(x_str)
    if d == 0:
        return 0, 0
    if d < 0:
        s, d = 1, -d
    else:
        s = 0
    d *= twoTo56
    e = 64
    while d < twoTo52:
        e -= 1
        d *= 16
    while d >= twoTo56:
        e += 1
        d /= 16
    f = int(d.to_integral_value(rounding=mode))
    msw = ((s << 31) | (e << 24) | (f >> 32)) & 0xFFFFFFFF
    lsw = f & 0xFFFFFFFF
    return msw, lsw


# Test cases: (literal, comment).
# 'D' marker would denote IBM double-quad, but our literals here are all
# regular decimals; the lexer treats them as DP automatically.
CASES = [
    # Canonical issue-ticket case — exact mantissa fractional 0.747...
    ("1.0E-8",      "issue #1296: known IBM=...1873, current HALSFC=...1874"),

    # Other small powers of 10 (decimal exponent) — also rounding-sensitive
    ("1E-9",        "fractional 0.795..."),
    ("1E-10",       "fractional 0.747..."),
    ("1.5E-7",      "fractional 0.512..."),
    ("3E-8",        "near-integer mantissa"),

    # The classic — 0.1 — round mode discriminator
    ("0.1",         "0x40199999_99999999 (truncated) vs ...9A (rounded)"),
    ("0.2",         "same family"),
    ("0.3",         ""),

    # Common math constants
    ("3.14159",                    "PI to 5dp"),
    ("3.141592653589793",          "PI to double precision"),
    ("2.718281828",                "e to 9dp"),
    ("2.718281828459045",          "e to double precision"),
    ("1.41421356",                 "sqrt(2) approx"),
    ("1.7320508",                  "sqrt(3) approx"),

    # Physical constants (large/small magnitudes)
    ("6.022E23",    "Avogadro"),
    ("1.602E-19",   "electron charge"),
    ("9.81",        "g (m/s^2)"),

    # Exact in IBM DP (rounding mode irrelevant)
    ("0.0",         "zero"),
    ("1.0",         "exact"),
    ("0.5",         "exact"),
    ("0.25",        "exact"),
    ("2.0",         "exact"),
    ("-2.5",        "exact, negative"),
    ("16.0",        "exact"),
    ("256.0",       "exact"),
    ("1E10",        "exact integer"),
    ("100000000",   "10^8 exact"),

    # Edge: very small / very large
    ("1E-50",       "small magnitude"),
    ("1E50",        "large magnitude"),
]


def main() -> None:
    print("# IBM DP hex float — expected values for HAL/S-FC float-literal regression")
    print("# Generated by test/float_literal/gen_expected.py")
    print("#")
    print("# columns: literal | IBM-truncate (correct) | round-half-up (current bug)")
    print("# Diff column flags rows where the rounding mode discriminates.")
    print()
    bug_count = 0
    for lit, comment in CASES:
        ms_t, ls_t = to_ibm_dp(lit, ROUND_DOWN)
        ms_r, ls_r = to_ibm_dp(lit, ROUND_HALF_UP)
        differ = (ms_t, ls_t) != (ms_r, ls_r)
        if differ:
            bug_count += 1
        flag = "  <-- DIFFERS" if differ else ""
        print(f"  {lit:<22}  trunc={ms_t:08X}_{ls_t:08X}  round={ms_r:08X}_{ls_r:08X}{flag}"
              + (f"  # {comment}" if comment else ""))
    print()
    print(f"# {bug_count}/{len(CASES)} cases discriminate truncation vs round-half-up.")


if __name__ == "__main__":
    main()
