"""Recover a DFG input deck from a DFG output COMPOOL.

The HAL/S COMPOOL source that's generated by the DFG contains the full
input deck as comments.  This script extracts it:

    dfginput CS0970            # deck to stdout
    dfginput -o DIR MEMBER...  # one deck file per member
"""
import os
import re
import sys
from typing import Annotated, Optional

os.environ["TYPER_USE_RICH"] = "0"  # disable fancy formatting
import typer

_CARD = re.compile(r"^.{7}[ 0-9]{6}([CM])\| (.*?)\s*\|  \|")
_TRAILER = re.compile(r"^\s*\*+\s*(REFERENCED COMPOOLS|BEGIN COMPOOL)")


def input_deck(lines):
    start = None
    for i, ln in enumerate(lines):
        m = _CARD.match(ln)
        if m and m.group(1) == "C" and "DFG INPUT" in m.group(2):
            start = i + 1
            break
    if start is None:
        return None
    cards = []
    for ln in lines[start:]:
        m = _CARD.match(ln)
        if not m:
            continue                   # page headers between print pages
        if m.group(1) == "M" or _TRAILER.match(m.group(2)):
            break                      # generated-compool body reached
        cards.append(m.group(2).rstrip())
    return cards


def extract_file(path):
    lines = open(path, errors="replace").read().splitlines()
    return input_deck(lines)


app = typer.Typer(
    help="Extract the input display deck echoed in a DFG output listing "
         "(its 'DFG INPUT' section).",
    add_completion=False,
    no_args_is_help=True,
    rich_markup_mode=None,
    pretty_exceptions_enable=False,
)


@app.command()
def main(
    listing: Annotated[list[str], typer.Argument(
        help="DFG output listing member(s), e.g. OI301700/APPLSRC/CS0970")],
    output_dir: Annotated[Optional[str], typer.Option("--output-dir", "-o",
        metavar="DIR",
        help="write one deck per listing to DIR (named after the member); "
             "default prints a single deck to stdout")] = None,
) -> None:
    if output_dir is None and len(listing) > 1:
        raise typer.BadParameter("multiple listings need -o DIR")

    failed = 0
    for path in listing:
        cards = extract_file(path)
        if cards is None:
            print("%s: not a DFG output listing (no DFG INPUT section)"
                  % path, file=sys.stderr)
            failed += 1
            continue
        text = "\n".join(cards) + "\n"
        if output_dir is None:
            sys.stdout.write(text)
        else:
            os.makedirs(output_dir, exist_ok=True)
            out = os.path.join(output_dir, os.path.basename(path))
            with open(out, "w") as f:
                f.write(text)
    if failed:
        raise typer.Exit(1)


if __name__ == "__main__":
    app()
